Update rust-bitcoin to 0.24.0
Blockstream/electrs pull request #31
Opened 2021-01-18 04:50 UTC by fujicoin

We suggest updating rust-bitcoin to version 0.24.0 of the original repository.

2021-01-18 11:19 UTC, dr-orlovsky commented
Why not 0.26?

2021-01-18 21:45 UTC, fujicoin commented
Fixed an issue where liquid could not compile.
It was necessary to update elements to 0.13.0, but with this it was necessary to update bitcoin to 0.25.

2021-01-19 23:02 UTC, shesek requested changes
Thanks @fujicoin! Upgrading rust-bitcoin and rust-elements is overdue.

I left a few comments. I'd also like to upgrade them to their latest versions, did you try that and run into any complications?

Will look into this myself soon if you won't beat me to it.

2021-01-19 23:02 UTC, shesek commented on src/daemon.rs
> +                    return Some((*target, -1_000f64));
Did you intend to change this as part of this PR?

2021-01-19 23:02 UTC, shesek commented on src/util/script.rs
> +        if let Some(Ok(PushBytes(redeemscript))) = txin.script_sig.instructions_minimal().last() {
Why `instructions_minimal`? This shouldn't be enforcing minimal pushes.

2021-01-19 23:02 UTC, shesek commented on src/new_index/schema.rs
> -        bincode::config()
This [was previously done](https://github.com/Blockstream/electrs/commit/51b2a8e655a95994d68157eadc5b8f180923ff27#diff-bc90c6e3075e12ca234e17791f751e2bf1ca9913295d3e3eb4c53cd885e7a032L26) and later [reverted](https://github.com/Blockstream/electrs/commit/5daf1e811af528d1d59f9fcf0de78ac371dd759a) because it was suspected to be related to a database issue we were experiencing. This is worth additional investigation, but shouldn't be part of this PR.

2021-01-19 23:02 UTC, shesek commented on Cargo.toml
> +rev = "0.13.0"
Maybe use the crate now that the changes needed are released?

2021-01-20 04:54 UTC, fujicoin commented
The latest TAG for rust-bitcoin is 0.25.2. So I think this update is OK. 
elements 0.13.0 specifies bitcoin  0.25 . The dependencies of TAG 0.14.0 and 0.15.0 are the same as 0.13.0. 
I haven't tried it, but I think it's possible to compile electrs with elements 0.15.0.

2021-01-20 05:02 UTC, fujicoin commented on src/daemon.rs
> +                    return Some((*target, -1_000f64));
If this is `None`, the electrum will disconnect the connection with the electrs.
Many altcoins like Fujicoin have few transactions so the fee estimate doesn't work. Electrum will set a minimum fee when a dummy negative answer is returned.
If it is desirable to expand esplora-electrs to altcoin, I think it is better to fix this.

2021-01-20 05:14 UTC, fujicoin commented on src/new_index/schema.rs
> -        bincode::config()
Fixed a warning that bincode :: config () should not be used during compilation. It doesn't seem to be a problem to me, but check back for database issues.

2021-01-20 05:19 UTC, fujicoin commented on Cargo.toml
> +rev = "0.13.0"
I think that's fine.

2021-01-20 05:26 UTC, fujicoin commented on src/util/script.rs
> +        if let Some(Ok(PushBytes(redeemscript))) = txin.script_sig.instructions_minimal().last() {
`.iter (true)` will result in the following compilation error.
```
error [E0599]: no method named `iter` found for struct` bitcoin :: blockdata :: script :: Script` in the current scope
   -> src / util / script.rs: 34: 68
```

2021-01-20 06:06 UTC, shesek commented on src/util/script.rs
> +        if let Some(Ok(PushBytes(redeemscript))) = txin.script_sig.instructions_minimal().last() {
There's an `instructions()` method too

2021-01-20 06:43 UTC, fujicoin commented on src/util/script.rs
> +        if let Some(Ok(PushBytes(redeemscript))) = txin.script_sig.instructions_minimal().last() {
In the case of `txin.script_sig.iter (true)`, when you look at the corresponding function of bitcoin 0.23.0, `enforce_minimal:` is set to `true` :
https://github.com/rust-bitcoin/rust-bitcoin/blob/2cba81935d0210cc32d3bdbaf0470f69708c109d/src/blockdata/script.rs#L332

`pub fn iter` is obsolete in bitcoin 0.25.2. The alternative part is as follows.

https://github.com/rust-bitcoin/rust-bitcoin/blob/46fdee5d88714be9367c5457ee0ad448f3803d96/src/blockdata/script.rs#L392

It says `To force minimal pushes, use [instructions_minimal] .`. So isn't `txin.script_sig.instructions_minimal ()` correct?

2021-01-20 07:14 UTC, dr-orlovsky commented
Just FYI, rust-bitcoin has 0.26 release already (a week ago)

2021-01-20 07:54 UTC, fujicoin commented
confirmed. The rust-bitcoin is certainly set to TAG 0.26.0 on January 15th.
But don't use 0.26.0 !
This is because the liquid cannot be compiled because it is inconsistent with the depends of rust-elements.

2021-01-20 17:31 UTC, dr-orlovsky commented
Ok, I heard they are working on updating liquid to 0.26 these days

2021-01-20 17:36 UTC, fujicoin commented on Cargo.toml
> +rev = "0.13.0"
Changed to use crate elements.
In conclusion, you should use 0.13.0.
0.14.0 has not been released to crate.
The following error occurs in 0.15.0.
```
error[E0433]: failed to resolve: could not find `bitcoin_hashes` in `elements`
 --> src/elements/registry.rs:8:15
  |
8 | use elements::bitcoin_hashes::hex::FromHex;
  |               ^^^^^^^^^^^^^^ could not find `bitcoin_hashes` in `elements`
```

2021-01-20 17:58 UTC, fujicoin commented
I think it is better to separate esplora-electrs for bitcoin and liquid because coding becomes complicated.

2021-01-28 14:48 UTC, shesek commented
I created a branch with rust-elements v0.15 and rust-bitcoin v0.26 (or v0.25 for liquid mode): https://github.com/Blockstream/electrs/commits/202101-deps

This will soon be merged to master.

2021-01-28 19:15 UTC, fujicoin commented
OK. Then I will close this PR.

2021-01-28 19:15 UTC, closed without merging